"""预置策略模板（公共策略库）。"""
from typing import Any

PRESET_STRATEGIES: list[dict[str, Any]] = [
    {
        "slug": "ma_cross_default",
        "name": "双均线 · 经典 20/50",
        "description": "日线金叉做多、死叉做空，适合趋势行情",
        "strategy_type": "ma_cross",
        "params": {"fast_ma": 20, "slow_ma": 50},
        "is_default": True,
    },
    {
        "slug": "ma_fast_10_30",
        "name": "双均线 · 灵敏 10/30",
        "description": "更短周期，信号更频繁",
        "strategy_type": "ma_cross",
        "params": {"fast_ma": 10, "slow_ma": 30},
    },
    {
        "slug": "ma_slow_50_200",
        "name": "双均线 · 稳健 50/200",
        "description": "长周期均线，过滤噪音、偏中长线",
        "strategy_type": "ma_cross",
        "params": {"fast_ma": 50, "slow_ma": 200},
    },
    {
        "slug": "ma_scalp_5_20",
        "name": "双均线 · 激进 5/20",
        "description": "超短均线组合，仅供对比测试",
        "strategy_type": "ma_cross",
        "params": {"fast_ma": 5, "slow_ma": 20},
    },
    {
        "slug": "rsi_14_30_70",
        "name": "RSI · 经典 14 (30/70)",
        "description": "脱离超卖做多、脱离超买做空",
        "strategy_type": "rsi",
        "params": {"period": 14, "oversold": 30, "overbought": 70},
    },
    {
        "slug": "rsi_14_35_65",
        "name": "RSI · 宽松 14 (35/65)",
        "description": "更宽阈值，信号略多",
        "strategy_type": "rsi",
        "params": {"period": 14, "oversold": 35, "overbought": 65},
    },
    {
        "slug": "macd_12_26_9",
        "name": "MACD · 标准 12/26/9",
        "description": "MACD 线与信号线金叉/死叉",
        "strategy_type": "macd",
        "params": {"fast": 12, "slow": 26, "signal": 9},
    },
    {
        "slug": "macd_8_21_5",
        "name": "MACD · 快速 8/21/5",
        "description": "更敏感 MACD 参数",
        "strategy_type": "macd",
        "params": {"fast": 8, "slow": 21, "signal": 5},
    },
    {
        "slug": "bollinger_20_2",
        "name": "布林带 · 20 轨 2σ",
        "description": "触及下轨反弹做多、触及上轨回落做空",
        "strategy_type": "bollinger",
        "params": {"period": 20, "std_dev": 2.0},
    },
    {
        "slug": "bollinger_20_25",
        "name": "布林带 · 20 轨 2.5σ",
        "description": "更宽轨道，信号更少更极端",
        "strategy_type": "bollinger",
        "params": {"period": 20, "std_dev": 2.5},
    },
    # —— 进阶趋势策略（推荐） ——
    {
        "slug": "donchian_turtle_20",
        "name": "★ 海龟突破 · 20 日通道",
        "description": "经典趋势跟踪，突破近期高低点入场，适合趋势行情",
        "strategy_type": "donchian",
        "params": {"entry_period": 20},
    },
    {
        "slug": "donchian_turtle_55",
        "name": "★ 海龟突破 · 55 日通道",
        "description": "长周期唐奇安，信号更少、偏中长线",
        "strategy_type": "donchian",
        "params": {"entry_period": 55},
    },
    {
        "slug": "macd_trend_12_26_50",
        "name": "★ MACD 趋势 · 12/26 + MA50",
        "description": "MACD 金叉/死叉叠加 50 日均线过滤，减少震荡假突破",
        "strategy_type": "macd_trend",
        "params": {"fast": 12, "slow": 26, "signal": 9, "trend_ma": 50},
    },
    {
        "slug": "macd_trend_12_26_200",
        "name": "★ MACD 趋势 · 12/26 + MA200",
        "description": "用 200 日均线定大势，适合美股/指数中长线",
        "strategy_type": "macd_trend",
        "params": {"fast": 12, "slow": 26, "signal": 9, "trend_ma": 200},
    },
    {
        "slug": "momentum_63_100",
        "name": "★ 动量趋势 · 63日 + MA100",
        "description": "约 3 个月动量配合 100 日均线，趋势确认后入场",
        "strategy_type": "momentum",
        "params": {"lookback": 63, "trend_ma": 100, "roc_threshold": 0.0},
    },
    {
        "slug": "momentum_126_200",
        "name": "★ 动量趋势 · 126日 + MA200",
        "description": "半年动量 + 200 日均线，偏稳健的中长线趋势",
        "strategy_type": "momentum",
        "params": {"lookback": 126, "trend_ma": 200, "roc_threshold": 0.02},
    },
    {
        "slug": "donchian_fast_10",
        "name": "唐奇安 · 10 日（激进）",
        "description": "短通道突破，信号多、适合波动大的品种测试",
        "strategy_type": "donchian",
        "params": {"entry_period": 10},
    },
]
